-- Seed the global exercise reference library.
-- Run after migrations: psql < supabase/seed/seed_exercises.sql
-- or paste into the Supabase SQL editor.

insert into public.exercises (id, name, primary_muscle, secondary_muscles, equipment, difficulty, instructions, form_cues, image_ref)
values
  ('ex-lat-pulldown', 'Lat Pulldown', 'back', '{biceps}', 'cable', 'beginner',
    '{"Sit and secure your thighs under the pad.","Grip the bar slightly wider than shoulder width.","Pull the bar down to your upper chest, leading with your elbows.","Control the bar back up to full arm extension."}',
    '{"Keep your chest up","Avoid leaning back excessively"}', 'lat-pulldown'),
  ('ex-chest-press', 'Chest Press (Machine)', 'chest', '{triceps,shoulders}', 'machine', 'new',
    '{"Adjust the seat so handles align with mid-chest.","Press the handles forward until arms are extended, not locked.","Return slowly to the starting position."}',
    '{"Keep shoulder blades pinned back","Exhale on the push"}', 'chest-press'),
  ('ex-seated-row', 'Seated Row', 'back', '{biceps,shoulders}', 'cable', 'beginner',
    '{"Sit with a slight bend in the knees, back straight.","Pull the handle toward your torso, squeezing shoulder blades together.","Extend arms fully with control."}',
    '{"Do not round your lower back","Keep elbows close to the body"}', 'seated-row'),
  ('ex-db-shoulder-press', 'Dumbbell Shoulder Press', 'shoulders', '{triceps}', 'dumbbell', 'beginner',
    '{"Sit or stand with a dumbbell in each hand at shoulder height.","Press overhead until arms are extended.","Lower back to shoulder height with control."}',
    '{"Avoid arching your lower back","Keep core braced"}', 'db-shoulder-press'),
  ('ex-cable-triceps-pushdown', 'Cable Triceps Pushdown', 'triceps', '{}', 'cable', 'new',
    '{"Grip the bar with elbows tucked to your sides.","Push down until arms are fully extended.","Return with control, keeping elbows fixed."}',
    '{"Keep elbows pinned to your ribs"}', 'triceps-pushdown'),
  ('ex-leg-press', 'Leg Press', 'quads', '{glutes,hamstrings}', 'machine', 'beginner',
    '{"Place feet shoulder-width on the platform.","Lower until knees form roughly a 90 degree angle.","Press back up without locking the knees."}',
    '{"Keep knees tracking over toes"}', 'leg-press'),
  ('ex-goblet-squat', 'Goblet Squat', 'quads', '{glutes,core}', 'dumbbell', 'beginner',
    '{"Hold a dumbbell close to your chest.","Squat down keeping your chest tall and heels grounded.","Drive back up through your heels."}',
    '{"Keep your chest tall","Do not let knees cave in"}', 'goblet-squat'),
  ('ex-romanian-deadlift', 'Dumbbell Romanian Deadlift', 'hamstrings', '{glutes,back}', 'dumbbell', 'intermediate',
    '{"Hold dumbbells in front of your thighs.","Hinge at the hips, lowering weights along your legs.","Return to standing by driving your hips forward."}',
    '{"Keep a soft bend in the knees","Keep the weights close to your legs"}', 'rdl'),
  ('ex-leg-curl', 'Seated Leg Curl', 'hamstrings', '{}', 'machine', 'new',
    '{"Adjust the pad to sit just above your heels.","Curl your legs down against the pad.","Return with control."}',
    '{"Avoid using momentum"}', 'leg-curl'),
  ('ex-bodyweight-squat', 'Bodyweight Squat', 'quads', '{glutes,core}', 'bodyweight', 'new',
    '{"Stand with feet shoulder-width apart.","Lower your hips back and down, keeping your chest up.","Push through your heels to stand."}',
    '{"Keep weight in your heels"}', 'bw-squat'),
  ('ex-pushup', 'Push-up', 'chest', '{triceps,shoulders,core}', 'bodyweight', 'beginner',
    '{"Start in a plank with hands under shoulders.","Lower your chest toward the floor.","Push back up to full extension."}',
    '{"Keep your body in a straight line","Do not let hips sag"}', 'pushup'),
  ('ex-resistance-band-row', 'Resistance Band Row', 'back', '{biceps}', 'resistance_band', 'new',
    '{"Anchor the band at chest height.","Pull the band toward your torso, squeezing your shoulder blades.","Return with control."}',
    '{"Keep elbows close to the body"}', 'band-row'),
  ('ex-plank', 'Plank', 'core', '{shoulders}', 'bodyweight', 'new',
    '{"Rest on forearms and toes, body in a straight line.","Brace your core and hold."}',
    '{"Do not let hips rise or sag"}', 'plank'),
  ('ex-treadmill-walk', 'Incline Treadmill Walk', 'cardio', '{glutes}', 'cardio_machine', 'new',
    '{"Set a moderate incline and comfortable pace.","Maintain an upright posture, avoid holding the rails."}',
    '{"Keep a pace where you can still hold a conversation"}', 'treadmill'),
  ('ex-lat-raise', 'Dumbbell Lateral Raise', 'shoulders', '{}', 'dumbbell', 'beginner',
    '{"Hold light dumbbells at your sides.","Raise arms out to shoulder height.","Lower with control."}',
    '{"Avoid swinging or using momentum","Lead with your elbows"}', 'lateral-raise'),
  ('ex-bicep-curl', 'Dumbbell Bicep Curl', 'biceps', '{}', 'dumbbell', 'new',
    '{"Hold dumbbells with arms extended, palms forward.","Curl the weights up toward your shoulders.","Lower with control."}',
    '{"Keep elbows pinned to your sides"}', 'bicep-curl'),
  ('ex-glute-bridge', 'Glute Bridge', 'glutes', '{hamstrings,core}', 'bodyweight', 'new',
    '{"Lie on your back, knees bent, feet flat.","Drive your hips up, squeezing your glutes at the top.","Lower with control."}',
    '{"Avoid overarching your lower back"}', 'glute-bridge'),
  ('ex-calf-raise', 'Standing Calf Raise', 'calves', '{}', 'bodyweight', 'new',
    '{"Stand tall, feet hip-width apart.","Rise onto the balls of your feet.","Lower with control below the starting height for a stretch."}',
    '{"Move slowly, avoid bouncing"}', 'calf-raise')
on conflict (id) do nothing;
